version: "3.9"

services:
  db:
    image: postgres:16
    container_name: autoria_postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  scraper:
    build: .
    container_name: autoria_scraper
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./dumps:/app/dumps
    command: python scheduler/scheduler.py

volumes:
  postgres_data:
  pgadmin_data:
